// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy3rU84zrOpzcWGkp22EYpywaxbbzh5uA',
    appId: '1:1064995614590:web:56f9077307c0b27fa74d2f',
    messagingSenderId: '1064995614590',
    projectId: 'safe-ride-325e8',
    authDomain: 'safe-ride-325e8.firebaseapp.com',
    storageBucket: 'safe-ride-325e8.firebasestorage.app',
    measurementId: 'G-NKV2ZKPL7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwfW5FVqxboswy9HGsQ8XMZhGg0qTYurA',
    appId: '1:1064995614590:android:568aec2647ce0eb7a74d2f',
    messagingSenderId: '1064995614590',
    projectId: 'safe-ride-325e8',
    storageBucket: 'safe-ride-325e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPhFyHFEHRFDpF98lzpsAAf9qC32d9ehA',
    appId: '1:1064995614590:ios:71406a0e0838245da74d2f',
    messagingSenderId: '1064995614590',
    projectId: 'safe-ride-325e8',
    storageBucket: 'safe-ride-325e8.firebasestorage.app',
    iosClientId: '1064995614590-5cucvtqceabhasshijpjtc06dt3hrbh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.saferide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPhFyHFEHRFDpF98lzpsAAf9qC32d9ehA',
    appId: '1:1064995614590:ios:71406a0e0838245da74d2f',
    messagingSenderId: '1064995614590',
    projectId: 'safe-ride-325e8',
    storageBucket: 'safe-ride-325e8.firebasestorage.app',
    iosClientId: '1064995614590-5cucvtqceabhasshijpjtc06dt3hrbh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.saferide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIFfA-H9FitxkXHcMlHjZ7ZAQjRSrA5ck',
    appId: '1:1064995614590:web:7931081fac96c9e0a74d2f',
    messagingSenderId: '1064995614590',
    projectId: 'safe-ride-325e8',
    authDomain: 'safe-ride-325e8.firebaseapp.com',
    storageBucket: 'safe-ride-325e8.firebasestorage.app',
    measurementId: 'G-RXVV26FT8T',
  );
}
